# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KontakAlamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KontakAlamofire

  target 'KontakAlamofireTests' do

    inherit! :search_paths
    
    # Pods for testing
    pod 'Alamofire'
    pod 'SwiftyJSON'
  end

  target 'KontakAlamofireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
